### ISSUE TITLE
Deprecated Node.js 12 actions (Update to Node.js 16)

### ISSUE THREAD

**Issue by michael-schnell** [crazy-max/ghaction-import-gpg#158]
The github build states:

> Node.js 12 actions are deprecated. Please update the following actions to use Node.js 16: crazy-max/ghaction-import-gpg@v4. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/.

Any plans to update?

**Comment by crazy-max** [comment]
Already since https://github.com/crazy-max/ghaction-import-gpg/releases/tag/v5.0.0

**Comment by michael-schnell** [comment]
Cool. Tnx.
