### ISSUE TITLE
openpgp is an outdated version that does not support ECC keys

### ISSUE THREAD

**Issue by AnomalRoil** [crazy-max/ghaction-import-gpg#74]
### Behaviour
Currently it appears this is using `"@types/openpgp": "^4.4.14"` to provide the [openpgpjs ](https://github.com/openpgpjs/openpgpjs) "bindings", sadly "@types/openpgp" hasn't been [updated in almost 4 years](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/16573). (Okay, [maybe only 2.5 years](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/26231)) And it seems stuck at version 4.4.14.

Current version is 4.10.9. It seems it is also an open issue here: https://github.com/openpgpjs/openpgpjs/issues/561

Most notably, `@types/openpgp` is missing support for **Elliptic curve keys** as this was included in openpgpjs 4.7.
ECC keys are really interesting because they are way smaller than RSA keys, and so they are nice to use for Github Secrets, IMO.

I believe according to the Openpgpjs issue that https://github.com/FlowCrypt/types is more up to date and maybe it might even work with 4.10. 
They are still working on it: https://github.com/FlowCrypt/types/issues/1 (but without the version tags, I'm afraid)

This might also be the cause of #71 

My proposal is to migrate to https://github.com/FlowCrypt/types instead.

#### Steps to reproduce this issue

1. Create a key using P-512:
    ```
   gpg --expert --full-generate-key
   // (10) ECC
   // (5) NIST P-512 
     ```
2. Add it using this action
3. See the same issue as here: https://github.com/gopasspw/gopass/runs/1730875607?check_suite_focus=true

#### Expected behaviour

The key should be imported and working as expected.

#### Actual behaviour

It fails says:
> Error: Could not find valid encryption key packet in key 

### Configuration
Not really relevant to the issue, but in case:

* Repository URL (if public): https://github.com/gopasspw/gopass
* Build URL (if public): https://github.com/gopasspw/gopass/runs/1730875607?check_suite_focus=true

**Comment by crazy-max** [comment]
@AnomalRoil Thanks for your report. I think we should wait for [v5 branch](https://github.com/openpgpjs/openpgpjs/tree/v5) to be merged that will include the [required/latest types definition](https://github.com/openpgpjs/openpgpjs/blob/v5/openpgp.d.ts).

**Comment by AnomalRoil** [comment]
I'm afraid we've replaced our ECC key with a RSA one, I might try and see if it works in a branch, but not sure.

**Comment by crazy-max** [comment]
@AnomalRoil It [should work](https://github.com/crazy-max/ghaction-import-gpg/runs/2230487358?check_suite_focus=true#step:4:115).
