### ISSUE TITLE
Suggestion: pass or allow `--global` flag when configuring properties in `git config`

### ISSUE THREAD

**Issue by JustArchi** [crazy-max/ghaction-import-gpg#92]
Hey,

I'm using your (awesome!) action in a workflow responsible for two different git repos, the root repo, and a git submodule repo which is a subdirectory in the root repo.

I'm using the same key for signing commits in both repos.

Unfortunately, your `git config` routine responsible for setting various properties, for example `user.email`, `user.name`, `user.signingkey` or `commit.gpgsign` does not pass the `--global` argument, in result being applied only to the repository in the `workdir` specified, which is my root repository by default.

My suggestion: add a boolean value, such as `global: true` in `with` properties, that would cause the `--global` argument to be passed to each call of `git config`.

This would allow me to use one import call for both of my repos, as opposed to my current approach which executes two different import calls with different `workdir` in order to set the git config values twice, one for each (local) repo.

See https://git-scm.com/docs/git-config documentation for more info on `--global` option.

Thank you in advance for your consideration in regards to his suggestion.

**Comment by crazy-max** [comment]
@JustArchi That's a good idea for this kind of behavior.

**Comment by JustArchi** [comment]
Thank you! 👍
