### ISSUE TITLE
Support `if-asked` for `git-push-gpgsign`

### ISSUE THREAD

**Issue by JustArchi** [crazy-max/ghaction-import-gpg#94]
As of today, GitHub does not support signed git pushes, therefore setting `git-push-gpgsign` to `true` will actually fail the push.

However, as the git manual states in https://git-scm.com/docs/git-config, you can actually set `push.gpgsign` to not only `false` and `true` values, but also `if-asked`, which will effectively sign the push if the resulting server supports it, and avoid a failure if it does not.

It'd probably be a good idea for `git-push-gpgsign` to support `if-asked` option in addition to `true` and `false`. I don't see a good reason why it shouldn't, and supporting it would allow us to bullet-proof for the future when GitHub (and probably a lot of other git servers) enable that option on their backends.

Thank you in advance for considering this feature.

**Comment by crazy-max** [comment]
@JustArchi SGTM, thanks for your feedback.

**Comment by JustArchi** [comment]
Thank you! 👍
